name: Docs
on:
  push:
    branches: [main]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: deploy
  cancel-in-progress: false
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Configure Rust for bare metal
        run: |
          rustup toolchain install nightly-2024-12-31
          rustup override set nightly-2024-12-31
          rustup component add rust-src
          rustup component add llvm-tools-preview
      - name: Configure cache
        uses: Swatinem/rust-cache@v2
      - name: Setup pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Clean docs folder
        run: cargo clean --doc
      - name: Build docs
        run: cargo doc --no-deps
      - name: Move docs to root
        run: cp -r target/x86_64-marcel_os/doc/marcel_os target/x86_64-marcel_os/doc/docs
      - name: Remove lock file
        run: rm target/x86_64-marcel_os//.lock
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/x86_64-marcel_os/doc/
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
